export enum BookingEventTypeEnum {
  BOOK_INIT = 'book:init',
  BOOK_PENDING = 'book:pending',
  BOOK_FAILED = 'book:failed',
  BOOK_CANCELLED = 'book:cancelled',
  BOOK_SUCCESS = 'book:success',
  PAYMENT_INIT = 'payment:init',
  PAYMENT_PROCESSING = 'payment:processing',
  PAYMENT_FAILED = 'payment:failed',
  PAYMENT_SUCCESS = 'payment:success',
  SEAT_RESERVATION_INIT = 'seat_reservation:init',
  SEAT_RESERVATION_UPDATE_INIT = 'seat_reservation:update_init',
  SEAT_RESERVATION_SUCCESS = 'seat_reservation:success',
  SEAT_RESERVATION_FAILED = 'seat_reservation:failed',
}
